/* Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

using System;
using System.Collections.Generic;
using System.Text;

namespace MongoDB.Bson.SourceGeneration.Generator
{
    // Produces the C# source for a context's generated serializers. The output shape
    // mirrors the hand-emitted reference at
    // tests/MongoDB.Bson.SourceGeneration.Tests/TestContext.HandEmitted.g.cs.
    internal static class Emitter
    {
        public static string Emit(ContextInfo context)
        {
            var sb = new StringBuilder(capacity: 4096);
            var hasNamespace = !string.IsNullOrEmpty(context.ContextNamespace);

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by MongoDB.Bson.SourceGeneration. Do not edit.");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            // No using directives: every emitted type name is global::-qualified so the file
            // compiles regardless of what's in scope at the consumer's namespace.

            string indent;
            if (hasNamespace)
            {
                sb.Append("namespace ").AppendLine(context.ContextNamespace);
                sb.AppendLine("{");
                indent = "    ";
            }
            else
            {
                indent = string.Empty;
            }

            sb.Append(indent).Append("partial class ").AppendLine(context.ContextName);
            sb.Append(indent).AppendLine("{");

            EmitDefaultProperty(sb, context, indent);
            EmitSerializerFields(sb, context, indent);
            EmitGetSerializer(sb, context, indent);

            var typesByFullName = BuildTypeIndex(context);
            foreach (var type in context.Types)
            {
                EmitSerializerClass(sb, type, typesByFullName, indent);
            }

            sb.Append(indent).AppendLine("}");

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitDefaultProperty(StringBuilder sb, ContextInfo context, string indent)
        {
            sb.Append(indent).Append("    public static ").Append(context.ContextName)
              .Append(" Default { get; } = new ").Append(context.ContextName).AppendLine("();");
            sb.AppendLine();
        }

        private static void EmitSerializerFields(StringBuilder sb, ContextInfo context, string indent)
        {
            foreach (var type in context.Types)
            {
                sb.Append(indent).Append("    private static readonly ")
                  .Append(SerializerClassName(type))
                  .Append(' ')
                  .Append(SerializerFieldName(type))
                  .Append(" = new ")
                  .Append(SerializerClassName(type))
                  .AppendLine("();");
            }
            sb.AppendLine();
        }

        private static void EmitGetSerializer(StringBuilder sb, ContextInfo context, string indent)
        {
            sb.Append(indent).AppendLine("    public override global::MongoDB.Bson.Serialization.IBsonSerializer? GetSerializer(global::System.Type type)");
            sb.Append(indent).AppendLine("    {");

            foreach (var type in context.Types)
            {
                sb.Append(indent).Append("        if (type == typeof(")
                  .Append(type.TypeFullName)
                  .Append(")) { return ")
                  .Append(SerializerFieldName(type))
                  .AppendLine("; }");
            }

            sb.Append(indent).AppendLine("        return null;");
            sb.Append(indent).AppendLine("    }");
            sb.AppendLine();
        }

        private static Dictionary<string, TypeToGenerate> BuildTypeIndex(ContextInfo context)
        {
            var dict = new Dictionary<string, TypeToGenerate>(context.Types.Count);
            foreach (var t in context.Types)
            {
                dict[t.TypeFullName] = t;
            }
            return dict;
        }

        private static void EmitSerializerClass(
            StringBuilder sb,
            TypeToGenerate type,
            Dictionary<string, TypeToGenerate> typesByFullName,
            string indent)
        {
            var i = indent + "    ";
            sb.Append(i).Append("private sealed class ").Append(SerializerClassName(type))
              .Append(" : global::MongoDB.Bson.Serialization.Serializers.SerializerBase<").Append(type.TypeFullName).AppendLine(">");
            sb.Append(i).AppendLine("{");

            EmitMemberSerializerFields(sb, type, i);
            EmitDeserialize(sb, type, typesByFullName, i);
            EmitDeserializeCore(sb, type, i);
            EmitSerialize(sb, type, typesByFullName, i);

            sb.Append(i).AppendLine("}");
            sb.AppendLine();
        }

        // Members with [BsonSerializer(typeof(X))] or [BsonRepresentation(BsonType.X)] route their
        // reads/writes through a cached serializer instance instead of the inline primitive path.
        // Fields are scoped to the per-type serializer class — member names are unique within a
        // POCO, so the per-member name suffices.
        private static void EmitMemberSerializerFields(StringBuilder sb, TypeToGenerate type, string indent)
        {
            var anyEmitted = false;
            foreach (var m in type.Members)
            {
                var ov = GetMemberSerializerOverride(m);
                if (ov is null) { continue; }
                sb.Append(indent).Append("    private static readonly ").Append(ov.Value.FieldType)
                  .Append(' ').Append(MemberSerializerFieldName(m)).Append(" = ")
                  .Append(ov.Value.InitExpression).AppendLine(";");
                anyEmitted = true;
            }
            if (anyEmitted) { sb.AppendLine(); }
        }

        private static void EmitDeserialize(
            StringBuilder sb,
            TypeToGenerate type,
            Dictionary<string, TypeToGenerate> typesByFullName,
            string indent)
        {
            var i = indent + "    ";
            sb.Append(i).Append("public override ").Append(type.TypeFullName)
              .AppendLine(" Deserialize(global::MongoDB.Bson.Serialization.BsonDeserializationContext context, global::MongoDB.Bson.Serialization.BsonDeserializationArgs args)");
            sb.Append(i).AppendLine("{");
            sb.Append(i).AppendLine("    var reader = context.Reader;");
            sb.Append(i).AppendLine("    if (reader.GetCurrentBsonType() == global::MongoDB.Bson.BsonType.Null)");
            sb.Append(i).AppendLine("    {");
            sb.Append(i).AppendLine("        reader.ReadNull();");
            sb.Append(i).AppendLine("        return default!;");
            sb.Append(i).AppendLine("    }");
            sb.Append(i).AppendLine();

            if (type.KnownTypeFullNames.Count > 0)
            {
                EmitDeserializeDiscriminatorDispatch(sb, type, typesByFullName, i);
            }
            else
            {
                sb.Append(i).AppendLine("    return DeserializeCore(context, args);");
            }

            sb.Append(i).AppendLine("}");
            sb.AppendLine();
        }

        // Inline peek of _t + baked switch on subtype discriminators, mirroring
        // BsonClassMapSerializer.cs:93-102 but without going through the runtime registry for
        // in-context subtypes. Out-of-context subtypes fall through to the runtime convention so
        // the dispatch is still correct for arbitrarily registered types.
        private static void EmitDeserializeDiscriminatorDispatch(
            StringBuilder sb,
            TypeToGenerate type,
            Dictionary<string, TypeToGenerate> typesByFullName,
            string indent)
        {
            sb.Append(indent).AppendLine("    var __bookmark = reader.GetBookmark();");
            sb.Append(indent).AppendLine("    reader.ReadStartDocument();");
            sb.Append(indent).AppendLine("    string? __discriminator = null;");
            sb.Append(indent).AppendLine("    if (global::MongoDB.Bson.IO.IBsonReaderExtensions.FindElement(reader, \"_t\"))");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        var __bv = global::MongoDB.Bson.Serialization.Serializers.BsonValueSerializer.Instance.Deserialize(context, args);");
            sb.Append(indent).AppendLine("        if (__bv.IsString) { __discriminator = __bv.AsString; }");
            sb.Append(indent).AppendLine("        else if (__bv.IsBsonArray)");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            var __arr = __bv.AsBsonArray;");
            sb.Append(indent).AppendLine("            if (__arr.Count > 0 && __arr[__arr.Count - 1].IsString) { __discriminator = __arr[__arr.Count - 1].AsString; }");
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("    reader.ReturnToBookmark(__bookmark);");
            sb.AppendLine();
            sb.Append(indent).AppendLine("    switch (__discriminator)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        case null:");
            sb.Append(indent).Append("        case \"").Append(type.Discriminator).AppendLine("\":");
            sb.Append(indent).AppendLine("            return DeserializeCore(context, args);");

            foreach (var subtypeFullName in type.KnownTypeFullNames)
            {
                if (!typesByFullName.TryGetValue(subtypeFullName, out var subtype)) { continue; }
                // Skip the case if it duplicates the self discriminator (shouldn't happen in practice).
                if (subtype.Discriminator == type.Discriminator) { continue; }

                sb.Append(indent).Append("        case \"").Append(subtype.Discriminator).AppendLine("\":");
                sb.Append(indent).Append("            return (").Append(type.TypeFullName).Append(")")
                  .Append(SerializerFieldName(subtype)).AppendLine(".Deserialize(context, args);");
            }

            sb.Append(indent).AppendLine("        default:");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).Append("            var __conv = global::MongoDB.Bson.Serialization.BsonSerializer.LookupDiscriminatorConvention(typeof(")
              .Append(type.TypeFullName).AppendLine("));");
            sb.Append(indent).Append("            var __actualType = __conv.GetActualType(reader, typeof(")
              .Append(type.TypeFullName).AppendLine("));");
            sb.Append(indent).Append("            return (").Append(type.TypeFullName)
              .AppendLine(")global::MongoDB.Bson.Serialization.BsonSerializer.LookupSerializer(__actualType).Deserialize(context, args);");
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
        }

        // Emits `private static T DeserializeCore(...)`. Two construction paths share one body:
        //
        //   Path A (immediate): the type has a parameterless ctor and no init-only / required
        //     members. We declare `var result = new T();` up front and each switch case assigns
        //     `result.X = …` directly. Honors ctor-provided defaults for members not in the BSON.
        //
        //   Path B (deferred): the type has either no parameterless ctor (positional records) or
        //     at least one init-only / required member. We declare a `_local_X` per member, read
        //     into the locals, then construct with `new T(ctor_locals…) { init = … }` and
        //     post-assign plain settable members.
        //
        // The structural shape — header, read loop, _t case, switch cases, [BsonRequired] /
        // [BsonDefaultValue] post-checks — is identical; only the assignment target differs and
        // Path B has a construction tail. `targetOf` picks the right form for each member.
        //
        // Path B limitation: class-level field initializers on init/required members are NOT
        // honored when the BSON omits them; the local stays at `default(T)` and overwrites
        // whatever the class-level initializer set. Matches the reflection path's
        // `FormatterServices.GetUninitializedObject` behavior for types without a parameterless ctor.
        private static void EmitDeserializeCore(StringBuilder sb, TypeToGenerate type, string indent)
        {
            // "Was this element seen?" tracking drives [BsonRequired] (throw if missing) and
            // [BsonDefaultValue] (assign default if missing) after the read loop.
            var trackedNames = new HashSet<string>();
            foreach (var m in type.Members)
            {
                if (m.Required || m.DefaultValueExpression is not null) { trackedNames.Add(m.Name); }
            }

            var deferred = NeedsDeferredConstruction(type);
            string TargetOf(MemberToGenerate m) => deferred ? "_local_" + m.Name : "result." + m.Name;

            var i = indent + "    ";

            sb.Append(i).Append("private static ").Append(type.TypeFullName)
              .AppendLine(" DeserializeCore(global::MongoDB.Bson.Serialization.BsonDeserializationContext context, global::MongoDB.Bson.Serialization.BsonDeserializationArgs args)");
            sb.Append(i).AppendLine("{");
            sb.Append(i).AppendLine("    var reader = context.Reader;");
            sb.Append(i).AppendLine("    reader.ReadStartDocument();");

            // Pre-loop declarations.
            if (deferred)
            {
                foreach (var m in type.Members)
                {
                    sb.Append(i).Append("    ").Append(m.TypeFullName).Append(" _local_").Append(m.Name).AppendLine(" = default!;");
                }
            }
            else
            {
                sb.Append(i).Append("    var result = new ").Append(type.TypeFullName).AppendLine("();");
            }
            foreach (var name in trackedNames)
            {
                sb.Append(i).Append("    bool _seen_").Append(name).AppendLine(" = false;");
            }

            // Read loop.
            sb.Append(i).AppendLine("    while (reader.ReadBsonType() != global::MongoDB.Bson.BsonType.EndOfDocument)");
            sb.Append(i).AppendLine("    {");
            sb.Append(i).AppendLine("        var name = global::MongoDB.Bson.IO.IBsonReaderExtensions.ReadName(reader);");
            sb.Append(i).AppendLine("        switch (name)");
            sb.Append(i).AppendLine("        {");

            if (type.WriteDiscriminatorWhenSelf)
            {
                sb.Append(i).AppendLine("            case \"_t\": reader.SkipValue(); break;");
            }

            foreach (var m in type.Members)
            {
                if (m.IsExtraElements) { continue; }
                sb.Append(i).Append("            case \"").Append(m.ElementName).Append("\": ").Append(TargetOf(m)).Append(" = ");
                EmitReadExpression(sb, m);
                sb.Append(";");
                if (trackedNames.Contains(m.Name))
                {
                    sb.Append(" _seen_").Append(m.Name).Append(" = true;");
                }
                sb.AppendLine(" break;");
            }

            EmitDeserializeDefaultCase(sb, type, i, useLocalTarget: deferred);

            sb.Append(i).AppendLine("        }");
            sb.Append(i).AppendLine("    }");
            sb.Append(i).AppendLine("    reader.ReadEndDocument();");

            // [BsonRequired] / [BsonDefaultValue] post-checks against the chosen target.
            foreach (var m in type.Members)
            {
                if (m.Required)
                {
                    sb.Append(i).Append("    if (!_seen_").Append(m.Name).Append(") { throw new global::MongoDB.Bson.BsonSerializationException(\"Required member '")
                      .Append(m.Name).Append("' of ").Append(type.TypeFullName).AppendLine(" was not found in the BSON document.\"); }");
                }
                else if (m.DefaultValueExpression is not null)
                {
                    sb.Append(i).Append("    if (!_seen_").Append(m.Name).Append(") { ").Append(TargetOf(m)).Append(" = ")
                      .Append(m.DefaultValueExpression).AppendLine("; }");
                }
            }

            // Path B only: ctor invocation, initializer block for init/required slots, post-construction
            // assignments for plain settable members.
            if (deferred)
            {
                EmitDeferredConstruction(sb, type, i);
            }

            sb.Append(i).AppendLine("    return result;");
            sb.Append(i).AppendLine("}");
            sb.AppendLine();
        }

        // Emits the Path B construction tail: `var result = new T(ctor_locals…) { init = … };`
        // followed by `result.X = _local_X;` per plain settable member. Ctor parameters are
        // matched to members by case-insensitive name; unmatched params fall through to
        // `default(TParam)` (#6 diagnostic territory).
        private static void EmitDeferredConstruction(StringBuilder sb, TypeToGenerate type, string indent)
        {
            var ctorParamToMember = BuildCtorParamMatches(type);
            var matchedMemberNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var kv in ctorParamToMember) { matchedMemberNames.Add(kv.Value.Name); }

            sb.Append(indent).Append("    var result = new ").Append(type.TypeFullName).Append("(");
            for (var p = 0; p < type.ConstructorParameters.Count; p++)
            {
                if (p > 0) { sb.Append(", "); }
                if (ctorParamToMember.TryGetValue(p, out var matched))
                {
                    sb.Append("_local_").Append(matched.Name);
                }
                else
                {
                    sb.Append("default(").Append(type.ConstructorParameters[p].TypeFullName).Append(")");
                }
            }
            sb.Append(")");

            // Init-only / required members that weren't bound to a ctor param land in the object
            // initializer block. Compiler refuses `new T() { … }` if required members are missing,
            // so this is where they must go.
            var initSlot = new List<MemberToGenerate>();
            foreach (var m in type.Members)
            {
                if (matchedMemberNames.Contains(m.Name)) { continue; }
                if (m.IsInitOnly || m.IsRequired) { initSlot.Add(m); }
            }

            if (initSlot.Count > 0)
            {
                sb.AppendLine();
                sb.Append(indent).AppendLine("    {");
                for (var k = 0; k < initSlot.Count; k++)
                {
                    var m = initSlot[k];
                    sb.Append(indent).Append("        ").Append(m.Name).Append(" = _local_").Append(m.Name);
                    sb.AppendLine(k == initSlot.Count - 1 ? string.Empty : ",");
                }
                sb.Append(indent).AppendLine("    };");
            }
            else
            {
                sb.AppendLine(";");
            }

            // Everything else (plain settable, not bound to ctor) gets post-construction assignment.
            foreach (var m in type.Members)
            {
                if (matchedMemberNames.Contains(m.Name)) { continue; }
                if (m.IsInitOnly || m.IsRequired) { continue; }
                sb.Append(indent).Append("    result.").Append(m.Name).Append(" = _local_").Append(m.Name).AppendLine(";");
            }
        }

        // Builds a map from ctor-parameter index → matched MemberToGenerate, matching by
        // case-insensitive name (mirrors the runtime's NamedParameterCreatorMapConvention).
        // Params without a matching member are simply absent from the dictionary.
        private static Dictionary<int, MemberToGenerate> BuildCtorParamMatches(TypeToGenerate type)
        {
            var byName = new Dictionary<string, MemberToGenerate>(StringComparer.OrdinalIgnoreCase);
            foreach (var m in type.Members) { byName[m.Name] = m; }

            var matches = new Dictionary<int, MemberToGenerate>(type.ConstructorParameters.Count);
            for (var p = 0; p < type.ConstructorParameters.Count; p++)
            {
                if (byName.TryGetValue(type.ConstructorParameters[p].Name, out var m))
                {
                    matches[p] = m;
                }
            }
            return matches;
        }

        private static bool NeedsDeferredConstruction(TypeToGenerate type)
        {
            if (type.ConstructionStrategy == ConstructionStrategy.ParameterizedCtor) { return true; }
            foreach (var m in type.Members)
            {
                if (m.IsInitOnly || m.IsRequired) { return true; }
            }
            return false;
        }

        private static void EmitDeserializeDefaultCase(StringBuilder sb, TypeToGenerate type, string indent, bool useLocalTarget)
        {
            // Three-way decision tree, matching BsonClassMapSerializer.cs:218-231:
            //   1. [BsonExtraElements] catch-all → stash the value (wins over [BsonIgnoreExtraElements]).
            //   2. [BsonIgnoreExtraElements] → SkipValue.
            //   3. Otherwise → throw.
            var extras = FindExtraElementsMember(type);
            if (extras is not null)
            {
                EmitExtraElementsReadCase(sb, extras, indent, useLocalTarget);
                return;
            }

            if (type.IgnoreExtraElements)
            {
                sb.Append(indent).AppendLine("            default: reader.SkipValue(); break;");
                return;
            }
            sb.Append(indent).Append("            default: throw new global::MongoDB.Bson.BsonSerializationException(\"Element '\" + name + \"' was not expected for type ")
              .Append(type.TypeFullName).AppendLine(".\");");
        }

        private static void EmitExtraElementsReadCase(StringBuilder sb, MemberToGenerate m, string indent, bool useLocalTarget)
        {
            // Lazy-init the catch-all on first unknown element, matching DeserializeExtraElementMember
            // (BsonClassMapSerializer.cs:468-505). Path A writes to `result.X`; Path B (deferred
            // construction) writes to `_local_X` and assigns to the instance at construction time.
            var target = useLocalTarget ? "_local_" + m.Name : "result." + m.Name;
            sb.Append(indent).AppendLine("            default:");
            sb.Append(indent).AppendLine("            {");
            sb.Append(indent).Append("                if (").Append(target).AppendLine(" is null)");
            sb.Append(indent).AppendLine("                {");
            sb.Append(indent).Append("                    ").Append(target).Append(" = ").Append(m.ExtraElementsConstructor).AppendLine(";");
            sb.Append(indent).AppendLine("                }");
            sb.Append(indent).AppendLine("                var bsonValue = global::MongoDB.Bson.Serialization.Serializers.BsonValueSerializer.Instance.Deserialize(context, args);");
            if (m.ExtraElementsKind == ExtraElementsKind.BsonDocument)
            {
                sb.Append(indent).Append("                ").Append(target).AppendLine("[name] = bsonValue;");
            }
            else
            {
                sb.Append(indent).Append("                ").Append(target).AppendLine("[name] = global::MongoDB.Bson.BsonTypeMapper.MapToDotNetValue(bsonValue);");
            }
            sb.Append(indent).AppendLine("                break;");
            sb.Append(indent).AppendLine("            }");
        }

        private static MemberToGenerate? FindExtraElementsMember(TypeToGenerate type)
        {
            foreach (var m in type.Members)
            {
                if (m.IsExtraElements) { return m; }
            }
            return null;
        }

        private static void EmitSerialize(
            StringBuilder sb,
            TypeToGenerate type,
            Dictionary<string, TypeToGenerate> typesByFullName,
            string indent)
        {
            var i = indent + "    ";
            sb.Append(i).Append("public override void Serialize(global::MongoDB.Bson.Serialization.BsonSerializationContext context, global::MongoDB.Bson.Serialization.BsonSerializationArgs args, ")
              .Append(type.TypeFullName).AppendLine(" value)");
            sb.Append(i).AppendLine("{");
            sb.Append(i).AppendLine("    var writer = context.Writer;");

            if (type.IsReferenceType)
            {
                sb.Append(i).AppendLine("    if (value is null)");
                sb.Append(i).AppendLine("    {");
                sb.Append(i).AppendLine("        writer.WriteNull();");
                sb.Append(i).AppendLine("        return;");
                sb.Append(i).AppendLine("    }");
                sb.AppendLine();
            }

            // Polymorphic dispatch on the actual runtime type. Mirrors BsonClassMapSerializer.cs:649-665
            // where the runtime checks `obj.GetType()` and re-dispatches to the actual type's serializer.
            if (type.KnownTypeFullNames.Count > 0)
            {
                EmitSerializeDiscriminatorDispatch(sb, type, typesByFullName, i);
            }

            sb.Append(i).AppendLine("    writer.WriteStartDocument();");

            if (type.WriteDiscriminatorWhenSelf)
            {
                EmitDiscriminatorWrite(sb, type, i);
            }

            // Wire order is preserved: the [BsonExtraElements] member emits its loose key/value
            // pairs *in the slot it occupies* in the declared-member sequence, matching
            // BsonClassMapSerializer.SerializeClass which iterates AllMemberMaps in order
            // and special-cases the extras map (BsonClassMapSerializer.cs:588-665).
            foreach (var m in type.Members)
            {
                if (m.IsExtraElements)
                {
                    EmitExtraElementsWrite(sb, m, i);
                }
                else
                {
                    EmitMemberWrite(sb, m, i);
                }
            }

            sb.Append(i).AppendLine("    writer.WriteEndDocument();");
            sb.Append(i).AppendLine("}");
        }

        private static void EmitSerializeDiscriminatorDispatch(
            StringBuilder sb,
            TypeToGenerate type,
            Dictionary<string, TypeToGenerate> typesByFullName,
            string indent)
        {
            sb.Append(indent).AppendLine("    var __actualType = value.GetType();");
            sb.Append(indent).Append("    if (__actualType != typeof(").Append(type.TypeFullName).AppendLine("))");
            sb.Append(indent).AppendLine("    {");

            foreach (var subtypeFullName in type.KnownTypeFullNames)
            {
                if (!typesByFullName.TryGetValue(subtypeFullName, out var subtype)) { continue; }
                sb.Append(indent).Append("        if (__actualType == typeof(").Append(subtype.TypeFullName).AppendLine("))");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).Append("            ").Append(SerializerFieldName(subtype))
                  .Append(".Serialize(context, args, (").Append(subtype.TypeFullName).AppendLine(")value);");
                sb.Append(indent).AppendLine("            return;");
                sb.Append(indent).AppendLine("        }");
            }

            sb.Append(indent).AppendLine("        global::MongoDB.Bson.Serialization.BsonSerializer.LookupSerializer(__actualType).Serialize(context, args, value);");
            sb.Append(indent).AppendLine("        return;");
            sb.Append(indent).AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitDiscriminatorWrite(StringBuilder sb, TypeToGenerate type, string indent)
        {
            sb.Append(indent).AppendLine("    writer.WriteName(\"_t\");");
            sb.Append(indent).Append("    writer.WriteString(\"").Append(type.Discriminator).AppendLine("\");");
        }

        private static void EmitExtraElementsWrite(StringBuilder sb, MemberToGenerate m, string indent)
        {
            // Mirrors SerializeExtraElements (BsonClassMapSerializer.cs:600-628).
            sb.Append(indent).Append("    if (value.").Append(m.Name).AppendLine(" is not null)");
            sb.Append(indent).AppendLine("    {");
            if (m.ExtraElementsKind == ExtraElementsKind.BsonDocument)
            {
                sb.Append(indent).Append("        foreach (var element in value.").Append(m.Name).AppendLine(")");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            writer.WriteName(element.Name);");
                sb.Append(indent).AppendLine("            global::MongoDB.Bson.Serialization.Serializers.BsonValueSerializer.Instance.Serialize(context, args, element.Value);");
                sb.Append(indent).AppendLine("        }");
            }
            else
            {
                sb.Append(indent).Append("        foreach (var key in value.").Append(m.Name).AppendLine(".Keys)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            writer.WriteName(key);");
                sb.Append(indent).Append("            var elementValue = value.").Append(m.Name).AppendLine("[key];");
                sb.Append(indent).AppendLine("            var bsonValue = global::MongoDB.Bson.BsonTypeMapper.MapToBsonValue(elementValue);");
                sb.Append(indent).AppendLine("            global::MongoDB.Bson.Serialization.Serializers.BsonValueSerializer.Instance.Serialize(context, args, bsonValue);");
                sb.Append(indent).AppendLine("        }");
            }
            sb.Append(indent).AppendLine("    }");
        }

        private static void EmitMemberWrite(StringBuilder sb, MemberToGenerate m, string indent)
        {
            // Decide whether to wrap the WriteName + Write pair in a condition.
            // - [BsonIgnoreIfDefault] subsumes [BsonIgnoreIfNull] for reference types (default == null) and
            //   handles value types correctly via EqualityComparer<T>.Default — so it wins when both are set.
            // - [BsonIgnoreIfNull] only gets a real check on null-allowing types; on non-nullable value types
            //   it would be a tautology, so we emit unconditionally to avoid a noisy "always-true" warning.
            string? condition = null;
            if (m.IgnoreIfDefault)
            {
                condition = "!global::System.Collections.Generic.EqualityComparer<" + m.TypeFullName +
                            ">.Default.Equals(value." + m.Name + ", default(" + m.TypeFullName + "))";
            }
            else if (m.IgnoreIfNull && m.AllowsNull)
            {
                condition = "value." + m.Name + " is not null";
            }

            if (condition is null)
            {
                sb.Append(indent).Append("    writer.WriteName(\"").Append(m.ElementName).AppendLine("\");");
                sb.Append(indent).Append("    ");
                EmitWriteStatement(sb, m);
                sb.AppendLine();
                return;
            }

            sb.Append(indent).Append("    if (").Append(condition).AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        writer.WriteName(\"").Append(m.ElementName).AppendLine("\");");
            sb.Append(indent).Append("        ");
            EmitWriteStatement(sb, m);
            sb.AppendLine();
            sb.Append(indent).AppendLine("    }");
        }

        private static void EmitReadExpression(StringBuilder sb, MemberToGenerate member)
        {
            if (GetMemberSerializerOverride(member) is not null)
            {
                sb.Append(MemberSerializerFieldName(member)).Append(".Deserialize(context, args)");
                return;
            }

            switch (member.PrimitiveKind)
            {
                case PrimitiveKind.Boolean: sb.Append("reader.ReadBoolean()"); break;
                case PrimitiveKind.Int32: sb.Append("reader.ReadInt32()"); break;
                case PrimitiveKind.Int64: sb.Append("reader.ReadInt64()"); break;
                case PrimitiveKind.Double: sb.Append("reader.ReadDouble()"); break;
                case PrimitiveKind.String: sb.Append("reader.ReadString()"); break;
                case PrimitiveKind.ObjectId: sb.Append("reader.ReadObjectId()"); break;
                case PrimitiveKind.Decimal128: sb.Append("reader.ReadDecimal128()"); break;
                default:
                    sb.Append("(").Append(member.TypeFullName).Append(")global::MongoDB.Bson.Serialization.BsonSerializer.LookupSerializer(typeof(")
                      .Append(member.TypeFullName).Append(")).Deserialize(context, args)");
                    break;
            }
        }

        private static void EmitWriteStatement(StringBuilder sb, MemberToGenerate member)
        {
            if (GetMemberSerializerOverride(member) is not null)
            {
                sb.Append(MemberSerializerFieldName(member)).Append(".Serialize(context, args, value.")
                  .Append(member.Name).Append(");");
                return;
            }

            switch (member.PrimitiveKind)
            {
                case PrimitiveKind.Boolean: sb.Append("writer.WriteBoolean(value.").Append(member.Name).Append(");"); break;
                case PrimitiveKind.Int32: sb.Append("writer.WriteInt32(value.").Append(member.Name).Append(");"); break;
                case PrimitiveKind.Int64: sb.Append("writer.WriteInt64(value.").Append(member.Name).Append(");"); break;
                case PrimitiveKind.Double: sb.Append("writer.WriteDouble(value.").Append(member.Name).Append(");"); break;
                case PrimitiveKind.String: sb.Append("writer.WriteString(value.").Append(member.Name).Append(");"); break;
                case PrimitiveKind.ObjectId: sb.Append("writer.WriteObjectId(value.").Append(member.Name).Append(");"); break;
                case PrimitiveKind.Decimal128: sb.Append("writer.WriteDecimal128(value.").Append(member.Name).Append(");"); break;
                default:
                    sb.Append("global::MongoDB.Bson.Serialization.BsonSerializer.LookupSerializer(typeof(").Append(member.TypeFullName)
                      .Append(")).Serialize(context, args, value.").Append(member.Name).Append(");");
                    break;
            }
        }

        // Decides whether a member needs a cached per-member serializer instance, and if so,
        // what type and how to construct it.
        //
        // Precedence: [BsonSerializer(typeof(X))] wins over [BsonRepresentation(BsonType.Y)].
        // Rationale: the user named a specific serializer; honoring representation on top of that
        // would require mutating their serializer, which the runtime convention doesn't promise.
        //
        // [BsonRepresentation] is only honored on members whose CLR type maps to a known
        // PrimitiveKind. Putting it on non-primitive members has no effect today; a diagnostic
        // will surface this in ticket #6.
        private static MemberOverride? GetMemberSerializerOverride(MemberToGenerate m)
        {
            if (m.CustomSerializerTypeFullName is not null)
            {
                return new MemberOverride(
                    FieldType: m.CustomSerializerTypeFullName,
                    InitExpression: "new " + m.CustomSerializerTypeFullName + "()");
            }

            if (m.RepresentationBsonType is not null)
            {
                var serializerType = PrimitiveSerializerType(m.PrimitiveKind);
                if (serializerType is not null)
                {
                    return new MemberOverride(
                        FieldType: serializerType,
                        InitExpression: "new " + serializerType + "(global::MongoDB.Bson.BsonType." + m.RepresentationBsonType + ")");
                }
            }

            return null;
        }

        // Mirrors the runtime's primitive-serializer set (under MongoDB.Bson.Serialization.Serializers).
        // Each accepts a `BsonType representation` constructor parameter — see
        // src/MongoDB.Bson/Serialization/Serializers/Int32Serializer.cs:53 et al.
        private static string? PrimitiveSerializerType(PrimitiveKind kind) => kind switch
        {
            PrimitiveKind.Boolean => "global::MongoDB.Bson.Serialization.Serializers.BooleanSerializer",
            PrimitiveKind.Int32 => "global::MongoDB.Bson.Serialization.Serializers.Int32Serializer",
            PrimitiveKind.Int64 => "global::MongoDB.Bson.Serialization.Serializers.Int64Serializer",
            PrimitiveKind.Double => "global::MongoDB.Bson.Serialization.Serializers.DoubleSerializer",
            PrimitiveKind.String => "global::MongoDB.Bson.Serialization.Serializers.StringSerializer",
            PrimitiveKind.ObjectId => "global::MongoDB.Bson.Serialization.Serializers.ObjectIdSerializer",
            PrimitiveKind.DateTime => "global::MongoDB.Bson.Serialization.Serializers.DateTimeSerializer",
            PrimitiveKind.Decimal128 => "global::MongoDB.Bson.Serialization.Serializers.Decimal128Serializer",
            PrimitiveKind.Guid => "global::MongoDB.Bson.Serialization.Serializers.GuidSerializer",
            PrimitiveKind.BinaryData => "global::MongoDB.Bson.Serialization.Serializers.ByteArraySerializer",
            _ => null
        };

        private static string MemberSerializerFieldName(MemberToGenerate m) =>
            "s_" + char.ToLowerInvariant(m.Name[0]) + m.Name.Substring(1) + "Serializer";

        private static string SerializerClassName(TypeToGenerate type) => type.TypeShortName + "Serializer";

        private static string SerializerFieldName(TypeToGenerate type) =>
            "s_" + char.ToLowerInvariant(type.TypeShortName[0]) + type.TypeShortName.Substring(1) + "Serializer";

        private readonly record struct MemberOverride(string FieldType, string InitExpression);
    }
}
