/* Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

using System;
using System.Threading;

namespace MongoDB.Bson.Serialization
{
    /// <summary>
    /// Base class for source-generated BSON serializer contexts. Derive a partial class from this
    /// type, decorate it with one or more
    /// <see cref="MongoDB.Bson.Serialization.Attributes.BsonSerializableAttribute"/> instances, and
    /// the source generator will emit the implementation that supplies a serializer for each listed
    /// type.
    /// </summary>
    /// <remarks>
    /// The context exposes a single <see cref="IBsonSerializationProvider"/> via <see cref="Provider"/>.
    /// It does not itself implement that interface — the registry-side <c>GetSerializer(Type)</c>
    /// mechanism is an implementation detail kept off the user-facing surface. Call
    /// <see cref="Register"/> at application startup to push <see cref="Provider"/> onto the BSON
    /// serializer provider stack. The provider is built lazily on first access, so a context that
    /// is declared but never registered pays no per-serializer initialization cost.
    /// </remarks>
    public abstract class BsonSerializerContext
    {
        // Lazy keeps the per-type serializer cache off the heap until something actually asks for
        // it (Register or Provider). ExecutionAndPublication mode is the default — only one thread
        // ever runs CreateProvider, the rest wait and observe the same instance.
        private readonly Lazy<IBsonSerializationProvider> _provider;
        private int _registered;

        /// <summary>
        /// Initializes a new instance. Subclasses are generated by the source generator and don't
        /// declare a constructor.
        /// </summary>
        protected BsonSerializerContext()
        {
            _provider = new Lazy<IBsonSerializationProvider>(CreateProvider);
        }

        /// <summary>
        /// Constructs the provider that backs <see cref="Provider"/>. Implemented by the source
        /// generator in the derived partial class; user code does not call this directly.
        /// </summary>
        protected abstract IBsonSerializationProvider CreateProvider();

        /// <summary>
        /// The serialization provider this context exposes. Built on first access and cached.
        /// Useful for direct integration with future builder-based registration paths; most users
        /// only need <see cref="Register"/>.
        /// </summary>
        public IBsonSerializationProvider Provider => _provider.Value;

        /// <summary>
        /// Registers <see cref="Provider"/> with the BSON serializer registry. Subsequent lookups
        /// for the context's listed types resolve through this context before any built-in provider.
        /// Calling this method more than once on the same instance is a no-op; the registry is a
        /// stack with no deduplication, so without this guard each repeat call would push the same
        /// provider again and lengthen every subsequent serializer lookup.
        /// </summary>
        public void Register()
        {
            if (Interlocked.CompareExchange(ref _registered, 1, 0) == 0)
            {
                BsonSerializer.RegisterSerializationProvider(_provider.Value);
            }
        }
    }
}
